name: Delete merged branch

on:
  push
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@v1.3.3
