name: Pack dotnet core library

on: push

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.0.100-preview9-014004"
      - run: dotnet pack
