name: Pack and publish dotnet core library

on: push

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.0.100-preview9-014004"
      - env: # Or as an environment variable
          nuget_key: ${{ secrets.NugetKey }}
        
        run: dotnet pack -c Release
        run: dotnet nuget push ServiceBlock/bin/Release/ServiceBlock.*.nupkg -k $nuget_key -s https://api.nuget.org/v3/index.json
        run: dotnet nuget push ServiceBlock.Interface/bin/Release/ServiceBlock.Interface.*.nupkg -k $nuget_key -s https://api.nuget.org/v3/index.json
        run: dotnet nuget push ServiceBlock.Templates/bin/Release/ServiceBlock.Templates.*.nupkg -k $nuget_key -s https://api.nuget.org/v3/index.json
