name: Test dotnet core library

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.101"
      - name: Test library
        run: dotnet test /p:CollectCoverage=true
